### ISSUE TITLE
tf.enableProdMode

### ISSUE THREAD

**Issue by camhart** [infinitered/nsfwjs#278]
Any reason why the library doesn't enable prod mode?  Should this be left up to the developer?  If so, should documentation point it out?

https://www.tensorflow.org/js/guide/platform_environment#flags

**Comment by GantMan** [comment]
That's an excellent question.

I didn't want to assume prod mode, because it's not something you can turn on and back off.  Enabling debug mode doesn't disable prod mode.  Even though it seems like those are switches, they both just turn on and not off.  (reference https://github.com/tensorflow/tfjs/issues/1972)

So I leave this to the site owner.

**Comment by GantMan** [comment]
BTW, if you'd like to contribute to the documentation stating to enable prod mode, I'd accept that PR!

**Comment by camhart** [comment]
Would you like to expose this through nsfwjs's apis, or make people import TF directly?
